### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Ilham1462** [agusgun/FakeImageDetector#11]
untuk dataset .csv parameter yang diambil apa saja ?

**Comment by ded5ec-vop** [comment]
I dont understand your language bro.

**Comment by Ilham1462** [comment]
bolehkah saya meminta datasetnya pak ?


Pada tanggal Sel, 11 Agu 2020 pukul 22.28 ded5ec-vop <
notifications@github.com> menulis:

**Comment by agusgun** [comment]
Please see other closed issues for the information about the dataset

**Comment by ded5ec-vop** [comment]
Actually even I raised a query on your project. Coz the for loop does not
work for me
