### ISSUE TITLE
DataSet Issue

### ISSUE THREAD

**Issue by praseedasuresh** [agusgun/FakeImageDetector#14]
hello agusgun, thank you for releasing the code, I try to download the datasets you used in the method. But there is no link to the dataset. Please tell me how can I get that dataset.

**Comment by agusgun** [comment]
Hello, thank you for your interest with this project!

Please kindly refer to the following issue about the dataset: Issue #1

**Comment by praseedasuresh** [comment]
I didn't get the link of the csv file dataset.csv
