### ISSUE TITLE
Motivation of using CNN

### ISSUE THREAD

**Issue by blueclowd** [agusgun/FakeImageDetector#16]
Hi @agusgun Thanks for sharing your work. Would you mind helping me with some of my queries?

After going through the work, I learned that the CNN learns to predict a categorical ELA image of the input image. Am I correct?
If so, since we have already know how to convert an input image to an ELA image using the function `convert_to_ela_image()`, i. e., we can calculate the 'ground truth' directly, may I know the idea of having a CNN model to do the conversion? Thanks

**Comment by agusgun** [comment]
The prediction label is whether the image is tampered with or not (1 or 0, binary classification).
If I understand your explanation correctly, we don't predict a categorical ELA image. 
We simply use ELA for our feature extraction purpose. After feature extraction, we use this ELA feature as input to the CNN which will predict whether the image is tampered with or not.

**Comment by blueclowd** [comment]
Got it. Thanks so much for the explanation.
