### ISSUE TITLE
Where is the pretrained model

### ISSUE THREAD

**Issue by tengshaofeng** [agusgun/FakeImageDetector#17]

**Comment by agusgun** [comment]
Hi, thank you for your interest.
Unfortunately, there is no pretrained model anymore. This model is fairly easy and fast to train as long as you have the data.

**Comment by tengshaofeng** [comment]
Thanks for you replay. Because I have no large scale of data, so I need the pretrained model.

**Comment by tengshaofeng** [comment]
Thanks, I will trained it myeself.
