### ISSUE TITLE
regarding dataset

### ISSUE THREAD

**Issue by harshaYoloSolo** [agusgun/FakeImageDetector#3]
can u please tell what is in dataset.csv

**Comment by agusgun** [comment]
Thank you for the question, you can see the answer at the closed issues

**Comment by ghost** [comment]
I had visited the closed issues but the website mentioned their for the dataset is not available now.
Please help me in getting these dataset. It would be very helpful for me.
Please contact me on srijansah@gmail.com

**Comment by agusgun** [comment]
Hello, I am really sorry for the late reply.

You can check this link [Kaggle](https://www.kaggle.com/sophatvathana/casia-dataset)

**Comment by ghost** [comment]
Can you please guide me if i can take input from user in this project and
display the output if image is fake or not..??
As at last is only shows the confusion matrix.

Pls help me out. I would be very grateful to you

**Comment by agusgun** [comment]
So, you can convert the image to the feature using this snippet:
`feature = array(convert_to_ela_image(row[0], 90).resize((128, 128))).flatten() / 255.0`

After that, just use:
`model.predict(feature)`

Voila you get the output :)

**Comment by ghost** [comment]
Hey,
I am finding an error while executing the "Model Training" part.
After a long time, the message is displayed by the browser that "failed to
start the application" and the kernal dies automatically.
Please help me out with it.
Its quite urgent.
Please find the attachment for the screenshots.

**Comment by agusgun** [comment]
Sorry, for the failed to start the application. I don't know about that because that is system related. As long as you follow the notebook and the convention carefully, and have much RAM. You can train the model. If you doesn't have much RAM, please train it with batch size. You can search it on google.

Thank you very much.

**Comment by ghost** [comment]
Can i try with less no. of images in dataset??

**Comment by agusgun** [comment]
Yes you can, but the accuracy of the model will become bad. You can train it with batch size if you want the accuracy still good and your system can manage it.

**Comment by ghost** [comment]
While executing this section of code, i am getting the following error upon
model prediction.
Due to my system configuration i have resized the image to 64,64 .
Please find the attachment

**Comment by ghost** [comment]
Sir,
The model predicts only one class of output i.e it gives the output [0.1]
for every input image.

Please help, i am really in need of this.
Waiting for your reply ASAP.

**Comment by ghost** [comment]
hello 

> So, you can convert the image to the feature using this snippet:
> `feature = array(convert_to_ela_image(row[0], 90).resize((128, 128))).flatten() / 255.0`
> 
> After that, just use:
> `model.predict(feature)`
> 
> Voila you get the output :)

@agusgun  using model.predict like how you told is giving an error. but when using model.predict(X-TRAIN) it works fine

**Comment by ghost** [comment]
so how can i use my own image to predict?
