### ISSUE TITLE
Execution

### ISSUE THREAD

**Issue by azerty-aft** [agusgun/FakeImageDetector#4]
Hello,

What is the final of your program, because you don't share the results of your  tests?

Thank you

**Comment by azerty-aft** [comment]
what should we have as output?

**Comment by agusgun** [comment]
The output is whether an image tampered or not

**Comment by navdeep1604** [comment]
can we use for photoshopped

**Comment by sajjadahmed0309** [comment]
how to save model and check our image using that model
