### ISSUE TITLE
Error while converting images into ELA images 

### ISSUE THREAD

**Issue by rajsaraiya009** [agusgun/FakeImageDetector#7]
Hello, I have a small doubt actually when I am trying to convert image into ELA i.e
"convert_to_ela_image('datasets/train/real/Au_ani_00001.jpg', 90)" I am getting an error that permission is denied. Can you please help where I am going wrong.

To be more specific about my error I am pasting my error below,

***** PermissionError: [Errno 13] Permission denied: 'C:\Users\saraiya.resaved.jpg' *****

Any help will be highly appreciated thanks in advance.

**Comment by TheBlue24** [comment]
I think it's related to permission.Take a look on this stackoverflow link https://stackoverflow.com/questions/41910583/errno-13-permission-denied-python/41910734
